### PR TITLE
Use kasechange in openapi-generator

### PR DESCRIPTION
**Pull request by nielsvanvelzen**
It parses some names slightly different then my solution did. For some names (like X64) this works better but for others (like is4K) it's worse.

I'm not sure if I like the previous names more then the current so I'd like to have some feedback first before merge.

### CODE REVIEW

**Review by Maxr1998 — DISMISSED** [review]
I prefer the new naming scheme in most cases, especially removing the underscore is a very good thing. `is4k` looks fine to me, as does `is3d` on its own, only `is3dFormat` looks a bit weird imo, but at least it's consistent.

**Comment by nielsvanvelzen** [comment]
Whoops, forgot to remove the unit tests for the textcase class. Will do that tomorrow.

**Review by Maxr1998 — APPROVED** [review]

**Comment by Maxr1998** [comment]
Should we wait for a review from @thornbill or can I just merge?

**Comment by nielsvanvelzen** [comment]
It's not too  big change but I'd still like @thornbill's opinion on it so let's wait a bit 😄

**Review by thornbill — APPROVED** [review]
:+1: LGTM

**Pull request merged**
